export const DRIVERS_2026 = [
    { number: 1, full_name: 'Lando Norris' },
    { number: 3, full_name: 'Max Verstappen' },
    { number: 5, full_name: 'Gabriel Bortoleto' },
    { number: 6, full_name: 'Isack Hadjar' },
    { number: 10, full_name: 'Pierre Gasly' },
    { number: 11, full_name: 'Sergio Pérez' },
    { number: 12, full_name: 'Kimi Antonelli' },
    { number: 14, full_name: 'Fernando Alonso' },
    { number: 16, full_name: 'Charles Leclerc' },
    { number: 18, full_name: 'Lance Stroll' },
    { number: 23, full_name: 'Alexander Albon' },
    { number: 27, full_name: 'Nico Hülkenberg' },
    { number: 30, full_name: 'Liam Lawson' },
    { number: 31, full_name: 'Esteban Ocon' },
    { number: 41, full_name: 'Arvid Lindblad' },
    { number: 43, full_name: 'Franco Colapinto' },
    { number: 44, full_name: 'Lewis Hamilton' },
    { number: 55, full_name: 'Carlos Sainz Jr.' },
    { number: 63, full_name: 'George Russell' },
    { number: 77, full_name: 'Valtteri Bottas' },
    { number: 81, full_name: 'Oscar Piastri' },
    { number: 87, full_name: 'Oliver Bearman' },
] as const;
