export const DRIVERS_2026 = [
    { number: 1, full_name: 'Lando Norris', code: 'NOR' },
    { number: 3, full_name: 'Max Verstappen', code: 'VER' },
    { number: 5, full_name: 'Gabriel Bortoleto', code: 'BOR' },
    { number: 6, full_name: 'Isack Hadjar', code: 'HAD' },
    { number: 10, full_name: 'Pierre Gasly', code: 'GAS' },
    { number: 11, full_name: 'Sergio Pérez', code: 'PER' },
    { number: 12, full_name: 'Kimi Antonelli', code: 'ANT' },
    { number: 14, full_name: 'Fernando Alonso', code: 'ALO' },
    { number: 16, full_name: 'Charles Leclerc', code: 'LEC' },
    { number: 18, full_name: 'Lance Stroll', code: 'STR' },
    { number: 23, full_name: 'Alexander Albon', code: 'ALB' },
    { number: 27, full_name: 'Nico Hülkenberg', code: 'HUL' },
    { number: 30, full_name: 'Liam Lawson', code: 'LAW' },
    { number: 31, full_name: 'Esteban Ocon', code: 'OCO' },
    { number: 41, full_name: 'Arvid Lindblad', code: 'LIN' },
    { number: 43, full_name: 'Franco Colapinto', code: 'COL' },
    { number: 44, full_name: 'Lewis Hamilton', code: 'HAM' },
    { number: 55, full_name: 'Carlos Sainz Jr.', code: 'SAI' },
    { number: 63, full_name: 'George Russell', code: 'RUS' },
    { number: 77, full_name: 'Valtteri Bottas', code: 'BOT' },
    { number: 81, full_name: 'Oscar Piastri', code: 'PIA' },
    { number: 87, full_name: 'Oliver Bearman', code: 'BEA' },
] as const;
